---
- name: Modification du fichier sources.list sur Debian
  hosts: test
  become: yes
  become_method: su
  tasks:
    - name: Commenter les lignes existantes de deb.debian.org
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb http://deb.debian.org/debian/ bullseye main'
        line: '#deb http://deb.debian.org/debian/ bullseye main'
        backrefs: yes

    - name: Commenter les lignes existantes de deb.debian.org (sources)
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb-src http://deb.debian.org/debian/ bullseye main'
        line: '#deb-src http://deb.debian.org/debian/ bullseye main'
        backrefs: yes

    - name: Commenter les lignes existantes pour bullseye-updates
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb http://deb.debian.org/debian/ bullseye-updates main'
        line: '#deb http://deb.debian.org/debian/ bullseye-updates main'
        backrefs: yes

    - name: Commenter les lignes existantes pour bullseye-updates (sources)
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb-src http://deb.debian.org/debian/ bullseye-updates main'
        line: '#deb-src http://deb.debian.org/debian/ bullseye-updates main'
        backrefs: yes

    - name: Commenter les lignes existantes de security.debian.org
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb http://security.debian.org/debian-security bullseye-security main'
        line: '#deb http://security.debian.org/debian-security bullseye-security main'
        backrefs: yes

    - name: Commenter les lignes existantes de security.debian.org (sources)
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^deb-src http://security.debian.org/debian-security bullseye-security main'
        line: '#deb-src http://security.debian.org/debian-security bullseye-security main'
        backrefs: yes

    - name: Ajouter les nouvelles lignes de carroll.lan.supplay.fr pour deb.debian.org
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: |
          deb http://carroll.lan.supplay.fr/deb.debian.org/debian/ bullseye main
          deb-src http://carroll.lan.supplay.fr/deb.debian.org/debian/ bullseye main
        insertafter: EOF
        create: yes

    - name: Ajouter les nouvelles lignes de carroll.lan.supplay.fr pour security.debian.org
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: |
          deb http://carroll.lan.supplay.fr/security.debian.org/debian-security/ bullseye-security main
          deb-src http://carroll.lan.supplay.fr/security.debian.org/debian-security/ bullseye-security main
        insertafter: EOF
        create: yes
