---
- name: Install Password Pusher on Ubuntu Server
  hosts: test
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Install Docker
      apt:
        name: docker
        state: latest
        update_cache: yes

    - name: Install Docker compose
      apt:
        name: docker-compose
        state: latest
        update_cache: yes

    - name: Pull and run Password Pusher Docker container
      docker_container:
        name: password_pusher
        image: pglombardo/pwpush:release
        state: started
        published_ports:
          - "5100:5100"
