---
- name: Configure Netplan
  hosts: all
  become: yes
  tasks:
    - name: Configure network settings
      copy:
        dest: /etc/netplan/01-netcfg.yaml
        content: |
          network:
            version: 2
            ethernets:
              eth0:
                dhcp4: no
                addresses:
                  - 192.168.100.122/24
                routes:
                  - to: default
                    via: 192.168.100.248
                nameservers:
                  addresses:
                    - 192.168.99.85
      notify:
        - apply netplan

  handlers:
    - name: apply netplan
      command: netplan apply
